name: "Setup Environment"
description: "Sets up the environment with Compact compiler, pnpm, and Node.js"

inputs:
  skip-compact:
    description: "Skip the fast compile step"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Cache turbo build setup
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: "22.x"
        cache: "pnpm"

    - name: Setup Compact Compiler
      if: ${{ inputs.skip-compact != 'true' }}
      uses: midnightntwrk/setup-compact-action@4130145456ad3f45934788dd4a65647eb283e658
      with:
        compact-version: "0.26.0"

    - name: Verify Compact Compiler Installation
      if: ${{ inputs.skip-compact != 'true' }}
      shell: bash
      run: |
        if ! command -v compact >/dev/null 2>&1; then
          echo "::error::Compact CLI not found in PATH"
          exit 1
        fi
        echo "✅ Compact CLI is available"
        compact --version || true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Install Turbo Globally
      shell: bash
      env:
        TURBO_MAJOR_VERSION: 2
        TURBO_TELEMETRY_DISABLED: 1
      run: pnpm install turbo@${{ env.TURBO_MAJOR_VERSION }} -g
