name: 'Setup Environment'
description: 'Sets up the environment with Compact compiler, pnpm, and Node.js'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Cache Compact compiler
      uses: actions/cache@v4
      with:
        path: ${{ env.COMPACT_HOME }}
        key: compact-compiler-0.23.0
        restore-keys: |
          compact-compiler-

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.4.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'pnpm'
    
    - name: Build compact package
      shell: bash
      run: |
        cd packages/compact
        pnpm install
        pnpm run build
        cd ../../

    - name: Validate build artifacts
      shell: bash
      run: |
        REQUIRED_FILES=(
          "packages/compact/dist/runCompiler.js"
          "packages/compact/dist/runBuilder.js"
        )
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error::❌ Missing required file: $file"
            exit 1
          fi
        done

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
