name: "Setup Environment"
description: "Sets up the environment with Compact compiler, pnpm, and Node.js"

inputs:
  skip-compact:
    description: "Skip the fast compile step"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Set Compact environment variables
      shell: bash
      env:
        COMPILER_VERSION: "0.26.0"
      run: |
        echo "COMPILER_VERSION=$COMPILER_VERSION" >> "$GITHUB_ENV"

    - name: Cache Compact developer tools
      id: cache-compact
      uses: actions/cache@v4
      with:
        path: ~/.compact
        key: compact-tools-${{ env.COMPILER_VERSION }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: '22.x'
        cache: 'pnpm'

    - name: Enable Corepack for Yarn
      shell: bash
      run: corepack enable

    - name: Build compact-tools submodule
      shell: bash
      run: |
        echo "📦 Building compact-tools submodule..."
        cd compact-tools
        yarn install --immutable
        yarn build
        echo "✅ compact-tools built successfully"

    - name: Validate compact-tools artifacts
      shell: bash
      run: |
        REQUIRED_FILES=(
          "compact-tools/packages/cli/dist/runCompiler.js"
          "compact-tools/packages/cli/dist/runBuilder.js"
        )
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error::❌ Missing required file: $file"
            exit 1
          fi
        done
        echo "✅ compact-tools artifacts validated"

    - name: Build compact-contracts submodule
      shell: bash
      run: |
        echo "📦 Building compact-contracts submodule..."
        cd compact-contracts
        yarn install --immutable
        SKIP_ZK=true yarn compact
        echo "✅ compact-contracts built successfully"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
