name: 'Setup Environment'
description: 'Sets up the environment with Compact compiler, pnpm, and Node.js'

inputs:
  skip-compile:
    description: 'Skip the fast compile step'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set Compact environment variables
      shell: bash
      run: |
        COMPACT_HOME="$HOME/compactc"
        echo "COMPACT_HOME=$COMPACT_HOME" >> "$GITHUB_ENV"
        echo "$COMPACT_HOME" >> "$GITHUB_PATH"

    - name: Cache Compact compiler
      id: cache-compact
      uses: actions/cache@v4
      with:
        path: ${{ env.COMPACT_HOME }}
        key: compact-compiler-0.23.0
        restore-keys: |
          compact-compiler-

    - name: Install Compact compiler
      if: steps.cache-compact.outputs.cache-hit != 'true'
      shell: bash
      env:
        COMPILER_VERSION: "0.23.0"
        LANGUAGE_VERSION: "0.15.0"
      run: |
        set -euo pipefail
        # Create directory for compiler
        mkdir -p "$COMPACT_HOME"

        # Create URL
        ZIP_FILE="compactc_v${COMPILER_VERSION}_x86_64-unknown-linux-musl.zip"
        DOWNLOAD_URL="https://d3fazakqrumx6p.cloudfront.net/artifacts/compiler/compactc_${COMPILER_VERSION}/${ZIP_FILE}"

        echo "⬇️ Downloading Compact compiler..."
        curl -Ls "$DOWNLOAD_URL" -o "$COMPACT_HOME/compactc.zip"

        echo "📦 Extracting..."
        unzip -qo "$COMPACT_HOME/compactc.zip" -d "$COMPACT_HOME"
        chmod +x "$COMPACT_HOME"/{compactc,compactc.bin,zkir}

    - name: Verify Compact compiler installation
      shell: bash
      run: |
        echo "✅ Verifying installation..."
        if [ ! -f "$COMPACT_HOME/compactc" ]; then
          echo "::error::❌ compactc not found in $COMPACT_HOME"
          exit 1
        fi

        echo "🤖 Testing installation..."
        "$COMPACT_HOME/compactc" --version

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.4.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'pnpm'
    
    - name: Build compact package
      shell: bash
      run: |
        cd packages/compact
        pnpm install
        pnpm run build
        cd ../../

    - name: Validate build artifacts
      shell: bash
      run: |
        REQUIRED_FILES=(
          "packages/compact/dist/runCompiler.js"
          "packages/compact/dist/runBuilder.js"
        )
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error::❌ Missing required file: $file"
            exit 1
          fi
        done

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Build contract packages (with retry on hash mismatch)
      if: inputs.skip-compile != 'true'
      shell: bash
      run: |
        set -euo pipefail

        build_contracts() {
          echo "⚙️ Building contract packages..."
          if ! pnpm build:contracts; then
            echo "❌ Build failed."
            if [ -d "$HOME/.cache/midnight/zk-params" ]; then
              echo "⚠️ zk-params exists. Removing cache and retrying..."
              rm -rf "$HOME/.cache/midnight/zk-params"
              echo "::notice::♻️ Retrying build after clearing zk-params..."
              pnpm build:contracts || { echo "::error::❌ Retry also failed."; exit 1; }
            else
              echo "🚫 Build failed and zk-params missing. No retry."
              exit 1
            fi
          fi
        }

        build_contracts
