name: 'Setup Environment'
description: 'Sets up the environment with Compact compiler, pnpm, and Node.js'

inputs:
  skip-compile:
    description: 'Skip the fast compile step'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install Compact compiler
      id: setup
      shell: bash
      run: |
        # Set version variables
        COMPILER_VERSION="0.23.0"
        LANGUAGE_VERSION="0.15.0"
        
        # Create directory for compiler
        COMPACT_HOME="$HOME/compactc"
        mkdir -p "$COMPACT_HOME"
        cd "$COMPACT_HOME"
        
        # Download and extract compiler
        curl -L https://d3fazakqrumx6p.cloudfront.net/artifacts/compiler/compactc_${COMPILER_VERSION}/compactc_v${COMPILER_VERSION}_x86_64-unknown-linux-musl.zip -o compactc.zip
        unzip compactc.zip

        # Make files executable
        chmod +x compactc.bin zkir compactc
        
        # Verify installation
        [ -f "$COMPACT_HOME/compactc" ] || { echo "::error::❌ Failed to install compiler - compactc not found"; exit 1; }
        
        # Test the compiler
        "$COMPACT_HOME/compactc" --version
        
        # Set up environment variables
        echo "COMPACT_HOME=$COMPACT_HOME" >> $GITHUB_ENV
        echo "$COMPACT_HOME" >> $GITHUB_PATH

    - name: Cache Compact compiler
      uses: actions/cache@v4
      with:
        path: ${{ env.COMPACT_HOME }}
        key: compact-compiler-0.23.0
        restore-keys: |
          compact-compiler-

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.4.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'pnpm'
    
    - name: Build compact package
      shell: bash
      run: |
        cd packages/compact
        pnpm install
        pnpm run build
        cd ../../

    - name: Validate build artifacts
      shell: bash
      run: |
        REQUIRED_FILES=(
          "packages/compact/dist/runCompiler.js"
          "packages/compact/dist/runBuilder.js"
        )
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error::❌ Missing required file: $file"
            exit 1
          fi
        done

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Fast compile contracts (skip zk)
      if: ${{ inputs.skip-compile != 'true' }}
      shell: bash
      run: pnpm compact -- --skip-zk
