name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: checks-${{ github.run_id }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Lint and Format
        run: pnpm lint:ci
        timeout-minutes: 10

      - name: Commitlint
        run: pnpm commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}

      - name: Spell Check with Typos
        uses: crate-ci/typos@bbaefadf97b0ec5fdc942684b647f1a6ab250274 # v1.46.0
        with:
          config: .github/workflows/config/typos.toml

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Checks failed. Cleaning up..."
          rm -rf contracts/*/src/artifacts/
