name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: checks-${{ github.run_id }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Lint and Format
        run: pnpm lint:ci
        timeout-minutes: 10

      - name: Commitlint
        run: pnpm commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}

      - name: Spell Check with Typos
        uses: crate-ci/typos@65120634e79d8374d1aa2f27e54baa0c364fff5a # v1.42.1
        with:
          config: .github/workflows/config/typos.toml

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Checks failed. Cleaning up..."
          rm -rf contracts/*/src/artifacts/
